name: qev3-config-app

channels:
  - defaults
  - conda-forge

dependencies:
  - python==3.7.7
  - plotly==4.4.1
  - pip==19.0.3
  - nodejs==14.4.0
  - httptools==0.0.13
  - pyserial==3.4
  - pyinstaller==3.6
  - sanic==19.6.3
  - numpy==1.18.5

  - pylint==2.4.4 # for linting when you code
  - black==19.10b0 # for autoformatting (when you save)

  - pip:
      - sanic-cors==0.9.9.post1
      - python-dotenv==0.10.5
      - git+git://github.com/CallumJHays/conda-pack@5c40cd38d0584cf037b4ee03c1f7625fedd9a782 # conda-pack with ability to pack modified packages (as we want to cache the jupyterlab install)
