name: qev3-config-app

channels:
  - conda-forge

dependencies:
  - bqplot==0.12.1
  - jupyterlab==1.1.4
  - plotly==4.4.1
  - pip==19.0.3
  - nodejs==11.14.0
  - httptools==0.0.13
  - pyserial==3.4
  - pyinstaller==3.6
  - sanic==19.6.3

  - pylint==2.4.4 # for linting when you code
  - black==19.10b0 # for autoformatting (when you save)

  - pip:
      - jupyter-plotly-dash==0.3.1
      - sanic-cors==0.9.9.post1
      - python-dotenv==0.10.5
      - git+git://github.com/CallumJHays/conda-pack@5c40cd38d0584cf037b4ee03c1f7625fedd9a782
